---
kind: pipeline
type: exec
os: linux
arch: amd64

name: CD

steps:
- name: remove old deployed version
  failure: ignore
  commands:
    - docker stop website
    - docker rm website
    - docker rmi website
- name: deploy new docker image
  commands:
    - docker build -t website .
    - docker run -d --name website -p 127.0.0.1:5000:5000 website
---
kind: signature
hmac: 4c8c78a78f9e5f79428e6769411ee5e8a9c05a740cdc8e02df8d59a96d52c63c

...
