---
kind: pipeline
type: exec
os: linux
arch: amd64

name: CD

steps:
- name: remove old deployed version
  failure: ignore
  commands:
    - docker stop website
    - docker rm website
    - docker rmi website
- name: prepare working directory
  commands:
    - git -C $WORKINGDIR pull pull main
  environment:
    WORKINGDIR:
      from_secret: workingDir
- name: deploy new docker image
  commands:
    - docker build -t website $WORKINGDIR
    - docker run -d --name website -p 127.0.0.1:5000:5000 website
  environment:
    WORKINGDIR:
      from_secret: workingDir
---
kind: signature
hmac: 3e1f325fdbfb3f1b4a7d6e153ba7672bb5a48752e5e8c333d09883864475d9c9

...
